### ISSUE TITLE
Failed to run a clickos on Xen. 

### ISSUE THREAD

**Issue by shashibici** [cnplab/clickos#4]
Hi, 

I am trying to build and run ClickOS from the source code. 
I have successfully compiled and built the image of ClickOS, clickos_x86_64/clickos_x86_64.gz. 
However, when I was trying to run the ClickOS as a DomU VM, I got errors.

System environment:
--------------------------------------------------------------------------------
1) Use OS X as a host.
2) Install VMware Fusion 
3) Install Debian 7.8.0-64bits as a guest OS inside VMware.
4) Compile and build Xen-4.4.1 from source code inside Debian.
5) Use Debian as Dom0. 

I use the following command to run ClickOS from Dom0:
1) cd /path/to/clickos/
2) xl create minios/config.xen

The error messages:
--------------------------------------------------------------------------
libxl: error: libxl.c:4594:libxl_set_vcpuaffinity: setting vcpu affinity: Invalid argument
libxl: warning: libxl.c:4608:libxl_set_vcpuaffinity_all: failed to set affinity for 0
libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: /etc/xen/scripts/vif-bridge online [-1] exited with error status 1
libxl: error: libxl_device.c:1085:device_hotplug_child_death_cb: script: Could not find bridge device xenbr0
libxl: error: libxl_create.c:1226:domcreate_attach_vtpms: unable to add nic devices
libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: /etc/xen/scripts/vif-bridge offline [-1] exited with error status 1
libxl: error: libxl_device.c:1085:device_hotplug_child_death_cb: script: Could not find bridge device xenbr0
Parsing config from minios/config.xen

Content of config.xen
--------------------------------------------------------------------------------
kernel		= './minios/build/clickos_x86_64'
vcpus		= '1'
cpus		        = '2'
memory		= '12'
vif		        = ['mac=00:15:17:15:5d:74,bridge=xenbr0']
name		= 'click0'
on_crash	        = 'preserve'

Information that might be helpful:
----------------------------------------------------------------------------------

The output of 'xl vcpu-list':

Name                                ID  VCPU   CPU State   Time(s) CPU Affinity
Domain-0                             0     0    0   r--      25.4  all
Domain-0                             0     1    1   -b-      14.4  all

The output of 'xl info':

host                   : debian-xen
release                : 3.2.0-4-amd64
version                : #1 SMP Debian 3.2.65-1+deb7u2
machine                : x86_64
nr_cpus                : 2
max_cpu_id             : 127
nr_nodes               : 1
cores_per_socket       : 1
threads_per_core       : 1
cpu_mhz                : 2194
hw_caps                : 0fabfbff:2c100800:00000000:00007f00:f7fa3223:00000000:00000021:000027ab
virt_caps              : hvm
total_memory           : 2047
free_memory            : 167
sharing_freed_memory   : 0
sharing_used_memory    : 0
outstanding_claims     : 0
free_cpus              : 0
xen_major              : 4
xen_minor              : 4
xen_extra              : .1
xen_version            : 4.4.1
xen_caps               : xen-3.0-x86_64 xen-3.0-x86_32p hvm-3.0-x86_32 hvm-3.0-x86_32p hvm-3.0-x86_64 
xen_scheduler          : credit
xen_pagesize           : 4096
platform_params        : virt_start=0xffff800000000000
xen_changeset          : 
xen_commandline        : placeholder
cc_compiler            : gcc (Debian 4.7.2-5) 4.7.2
cc_compile_by          : root
cc_compile_domain      : 
cc_compile_date        : Fri Feb 27 14:32:20 EST 2015
xend_config_format     : 4

The output of 'xl dmesg':

 Xen 4.4.1
(XEN) Xen version 4.4.1 (root@) (gcc (Debian 4.7.2-5) 4.7.2) debug=n Fri Feb 27 14:32:20 EST 2015
(XEN) Latest ChangeSet: 
(XEN) Bootloader: GRUB 1.99-27+deb7u2
(XEN) Command line: placeholder
(XEN) Video information:
(XEN)  VGA is text mode 80x25, font 8x16
(XEN) Disc information:
(XEN)  Found 1 MBR signatures
(XEN)  Found 1 EDD information structures
(XEN) Xen-e820 RAM map:
(XEN)  0000000000000000 - 000000000009e800 (usable)
(XEN)  000000000009e800 - 00000000000a0000 (reserved)
(XEN)  00000000000dc000 - 0000000000100000 (reserved)
(XEN)  0000000000100000 - 000000007fee0000 (usable)
(XEN)  000000007fee0000 - 000000007feff000 (ACPI data)
(XEN)  000000007feff000 - 000000007ff00000 (ACPI NVS)
(XEN)  000000007ff00000 - 0000000080000000 (usable)
(XEN)  00000000f0000000 - 00000000f8000000 (reserved)
(XEN)  00000000fec00000 - 00000000fec10000 (reserved)
(XEN)  00000000fee00000 - 00000000fee01000 (reserved)
(XEN)  00000000fffe0000 - 0000000100000000 (reserved)
(XEN) System RAM: 2047MB (2096632kB)
(XEN) ACPI: RSDP 000F6AC0, 0024 (r2 PTLTD )
(XEN) ACPI: XSDT 7FEEC65B, 005C (r1 INTEL  440BX     6040000 VMW   1324272)
(XEN) ACPI: FACP 7FEFEE73, 00F4 (r4 INTEL  440BX     6040000 PTL     F4240)
(XEN) ACPI: DSDT 7FEEDE9D, 10FD6 (r1 PTLTD  Custom    6040000 MSFT  3000001)
(XEN) ACPI: FACS 7FEFFFC0, 0040
(XEN) ACPI: BOOT 7FEEDE75, 0028 (r1 PTLTD  $SBFTBL$  6040000  LTP        1)
(XEN) ACPI: APIC 7FEED733, 0742 (r1 PTLTD  	 APIC    6040000  LTP        0)
(XEN) ACPI: MCFG 7FEED6F7, 003C (r1 PTLTD  $PCITBL$  6040000  LTP        1)
(XEN) ACPI: SRAT 7FEEC757, 08A8 (r2 VMWARE MEMPLUG   6040000 VMW         1)
(XEN) ACPI: HPET 7FEEC71F, 0038 (r1 VMWARE VMW HPET  6040000 VMW         1)
(XEN) ACPI: WAET 7FEEC6F7, 0028 (r1 VMWARE VMW WAET  6040000 VMW         1)
(XEN) Domain heap initialised
(XEN) Processor #0 6:6 APIC version 21
(XEN) Processor #2 6:6 APIC version 21
(XEN) IOAPIC[0]: apic_id 1, version 17, address 0xfec00000, GSI 0-23
(XEN) Enabling APIC mode:  Phys.  Using 1 I/O APICs
(XEN) Not enabling x2APIC: depends on iommu_supports_eim.
(XEN) Using scheduler: SMP Credit Scheduler (credit)
(XEN) Detected 2194.056 MHz processor.
(XEN) Initing memory sharing.
(XEN) xstate_init: using cntxt_size: 0x340 and states: 0x7
(XEN) I/O virtualisation disabled
(XEN) ENABLING IO-APIC IRQs
(XEN)  -> Using new ACK method
(XEN) Platform timer is 14.318MHz HPET
(XEN) Allocated console ring of 16 KiB.
(XEN) VMX: Supported advanced features:
(XEN)  - APIC TPR shadow
(XEN)  - Extended Page Tables (EPT)
(XEN)  - Virtual-Processor Identifiers (VPID)
(XEN)  - Virtual NMI
(XEN)  - MSR direct-access bitmap
(XEN)  - Unrestricted Guest
(XEN) HVM: ASIDs enabled.
(XEN) HVM: VMX enabled
(XEN) HVM: Hardware Assisted Paging (HAP) detected
(XEN) HVM: HAP page sizes: 4kB, 2MB
(XEN) Brought up 2 CPUs
(XEN) *** LOADING DOMAIN 0 ***
(XEN)  Xen  kernel: 64-bit, lsb, compat32
(XEN)  Dom0 kernel: 64-bit, PAE, lsb, paddr 0x1000000 -> 0x193e000
(XEN) PHYSICAL MEMORY ARRANGEMENT:
(XEN)  Dom0 alloc.:   0000000074000000->0000000078000000 (460919 pages to be allocated)
(XEN)  Init. ramdisk: 000000007da7f000->000000007f9ffe00
(XEN) VIRTUAL MEMORY ARRANGEMENT:
(XEN)  Loaded kernel: ffffffff81000000->ffffffff8193e000
(XEN)  Init. ramdisk: ffffffff8193e000->ffffffff838bee00
(XEN)  Phys-Mach map: ffffffff838bf000->ffffffff83c72fc0
(XEN)  Start info:    ffffffff83c73000->ffffffff83c734b4
(XEN)  Page tables:   ffffffff83c74000->ffffffff83c97000
(XEN)  Boot stack:    ffffffff83c97000->ffffffff83c98000
(XEN)  TOTAL:         ffffffff80000000->ffffffff84000000
(XEN)  ENTRY ADDRESS: ffffffff816aa200
(XEN) Dom0 has maximum 2 VCPUs
(XEN) Scrubbing Free RAM: .done.
(XEN) Initial low memory virq threshold set at 0x4000 pages.
(XEN) Std. Loglevel: Errors and warnings
(XEN) Guest Loglevel: Nothing (Rate-limited: Errors and warnings)
(XEN) Xen is relinquishing VGA console.
(XEN) *** Serial input -> DOM0 (type 'CTRL-a' three times to switch input to Xen)
(XEN) Freed 284kB init memory.

Best wishes,
Hongda

**Comment by fmanco** [comment]
Hi

You have to problems:

* The configuration file says `cpus = '2'` and you only have 2 cores. You should either remove the declaration or use another core (e.g `cpus = '1'`)
* The bridge `xenbr0` doesn't exist on your system. Create it or change to an existing bridge.

Best regards
Filipe

**Comment by shashibici** [comment]
Thank you so much for your comment, Filipe.
I have made ClickOS run on Xen virtual machine.


Hongda

**Comment by fmanco** [comment]
Great.

BR
Filipe

**Comment by ali1189** [comment]
xl vcpu-list:
Domain-0                             0     0   15   -b-      94.4  all
Domain-0                             0     1   14   r--     430.1  all
Domain-0                             0     2    2   -b-      80.6  all
Domain-0                             0     3    9   -b-      62.4  all
Domain-0                             0     4    8   -b-      22.5  all
Domain-0                             0     5    4   -b-      11.4  all
Domain-0                             0     6    6   -b-       5.1  all
Domain-0                             0     7    0   -b-       2.6  all
Domain-0                             0     8    7   -b-       2.0  all
Domain-0                             0     9    1   -b-       1.6  all
Domain-0                             0    10   17   -b-       1.8  all
Domain-0                             0    11   11   -b-       1.8  all
Domain-0                             0    12   21   -b-       3.9  all
Domain-0                             0    13    3   -b-     475.6  all
Domain-0                             0    14   20   -b-     108.3  all
Domain-0                             0    15   10   -b-      75.5  all
Domain-0                             0    16    5   -b-      25.4  all
Domain-0                             0    17   18   -b-      11.8  all
Domain-0                             0    18    1   -b-       5.7  all
Domain-0                             0    19   19   -b-       4.1  all
Domain-0                             0    20   12   -b-       3.8  all
Domain-0                             0    21   16   -b-       3.3  all
Domain-0                             0    22   22   -b-       3.9  all
Domain-0                             0    23   23   -b-       3.7  all
click0                               1     0    0   ---       0.0  all
click1                               3     0   12   ---      64.7  all
click2                               4     0    1   ---      37.8  all
click3                               5     0   13   r--     112.7  all

xl info:
host                   : debian
release                : 3.16.0-4-amd64
version                : #1 SMP Debian 3.16.43-2 (2017-04-30)
machine                : x86_64
nr_cpus                : 24
max_cpu_id             : 31
nr_nodes               : 4
cores_per_socket       : 12
threads_per_core       : 1
cpu_mhz                : 2200
hw_caps                : 178bf3ff:efd3fbff:00000000:00001300:00802001:00000000:000837ff:00000000
virt_caps              : hvm
total_memory           : 8190
free_memory            : 227
sharing_freed_memory   : 0
sharing_used_memory    : 0
outstanding_claims     : 0
free_cpus              : 0
xen_major              : 4
xen_minor              : 4
xen_extra              : .1
xen_version            : 4.4.1
xen_caps               : xen-3.0-x86_64 xen-3.0-x86_32p hvm-3.0-x86_32 hvm-3.0-x86_32p hvm-3.0-x86_64 
xen_scheduler          : credit
xen_pagesize           : 4096
platform_params        : virt_start=0xffff800000000000
xen_changeset          : 
xen_commandline        : placeholder
cc_compiler            : gcc (Debian 4.9.2-10) 4.9.2
cc_compile_by          : root
cc_compile_domain      : 
cc_compile_date        : Wed May 17 11:15:15 CEST 2017
xend_config_format     : 4

xl dmesg:

Xen 4.4.1
(XEN) Xen version 4.4.1 (root@fr.alcatel-lucent.com) (gcc (Debian 4.9.2-10) 4.9.2) debug=n Wed May 17 11:15:15 CEST 2017
(XEN) Latest ChangeSet: 
(XEN) Bootloader: GRUB 2.02~beta2-22+deb8u1
(XEN) Command line: placeholder
(XEN) Video information:
(XEN)  VGA is text mode 80x25, font 8x16
(XEN)  VBE/DDC methods: none; EDID transfer time: 0 seconds
(XEN)  EDID info not retrieved because no DDC retrieval method detected
(XEN) Disc information:
(XEN)  Found 1 MBR signatures
(XEN)  Found 1 EDD information structures
(XEN) Xen-e820 RAM map:
(XEN)  0000000000000000 - 000000000009a800 (usable)
(XEN)  000000000009a800 - 00000000000a0000 (reserved)
(XEN)  00000000000e6000 - 0000000000100000 (reserved)
(XEN)  0000000000100000 - 00000000dfe90000 (usable)
(XEN)  00000000dfe9e000 - 00000000dfea0000 type 9
(XEN)  00000000dfea0000 - 00000000dfeb2000 (ACPI data)
(XEN)  00000000dfeb2000 - 00000000dfee0000 (ACPI NVS)
(XEN)  00000000dfee0000 - 00000000f0000000 (reserved)
(XEN)  00000000ffe00000 - 0000000100000000 (reserved)
(XEN)  0000000100000000 - 0000000220000000 (usable)
(XEN) ACPI: RSDP 000FA0E0, 0024 (r2 ACPIAM)
(XEN) ACPI: XSDT DFEA0100, 0084 (r1 SMCI            20110708 MSFT       97)
(XEN) ACPI: FACP DFEA0290, 00F4 (r3 070811 FACP1507 20110708 MSFT       97)
(XEN) ACPI: DSDT DFEA06B0, 5B60 (r1  1A811 1A811000        0 INTL 20051117)
(XEN) ACPI: FACS DFEB2000, 0040
(XEN) ACPI: APIC DFEA0390, 0158 (r1 070811 APIC1507 20110708 MSFT       97)
(XEN) ACPI: MCFG DFEA04F0, 003C (r1 070811 OEMMCFG  20110708 MSFT       97)
(XEN) ACPI: OEMB DFEB2040, 0075 (r1 070811 OEMB1507 20110708 MSFT       97)
(XEN) ACPI: HPET DFEAA6B0, 0038 (r1 070811 OEMHPET  20110708 MSFT       97)
(XEN) ACPI: SRAT DFEAA6F0, 0250 (r2 AMD    AGESA           1 AMD         1)
(XEN) ACPI: SLIT DFEAA940, 003C (r1 AMD    AGESA           1 AMD         1)
(XEN) ACPI: SSDT DFEAA980, 3D8C (r1 A M I  POWERNOW        1 AMD         1)
(XEN) ACPI: EINJ DFEAE710, 0130 (r1  AMIER AMI_EINJ 20110708 MSFT       97)
(XEN) ACPI: BERT DFEAE8A0, 0030 (r1  AMIER AMI_BERT 20110708 MSFT       97)
(XEN) ACPI: ERST DFEAE8D0, 01B0 (r1  AMIER AMI_ERST 20110708 MSFT       97)
(XEN) ACPI: HEST DFEAEA80, 00A8 (r1  AMIER ABC_HEST 20110708 MSFT       97)
(XEN) System RAM: 8190MB (8386728kB)
(XEN) SRAT: Node 1 has no memory. BIOS Bug or mis-configured hardware?
(XEN) SRAT: Node 2 has no memory. BIOS Bug or mis-configured hardware?
(XEN) Domain heap initialised DMA width 30 bits
(XEN) Processor #16 0:9 APIC version 16
(XEN) Processor #17 0:9 APIC version 16
(XEN) Processor #18 0:9 APIC version 16
(XEN) Processor #19 0:9 APIC version 16
(XEN) Processor #20 0:9 APIC version 16
(XEN) Processor #21 0:9 APIC version 16
(XEN) Processor #22 0:9 APIC version 16
(XEN) Processor #23 0:9 APIC version 16
(XEN) Processor #24 0:9 APIC version 16
(XEN) Processor #25 0:9 APIC version 16
(XEN) Processor #26 0:9 APIC version 16
(XEN) Processor #27 0:9 APIC version 16
(XEN) Processor #32 0:9 APIC version 16
(XEN) Processor #33 0:9 APIC version 16
(XEN) Processor #34 0:9 APIC version 16
(XEN) Processor #35 0:9 APIC version 16
(XEN) Processor #36 0:9 APIC version 16
(XEN) Processor #37 0:9 APIC version 16
(XEN) Processor #38 0:9 APIC version 16
(XEN) Processor #39 0:9 APIC version 16
(XEN) Processor #40 0:9 APIC version 16
(XEN) Processor #41 0:9 APIC version 16
(XEN) Processor #42 0:9 APIC version 16
(XEN) Processor #43 0:9 APIC version 16
(XEN) IOAPIC[0]: apic_id 0, version 33, address 0xfec00000, GSI 0-23
(XEN) Enabling APIC mode:  Phys.  Using 1 I/O APICs
(XEN) Failed to get Error Log Address Range.
(XEN) Using scheduler: SMP Credit Scheduler (credit)
(XEN) Detected 2200.082 MHz processor.
(XEN) Initing memory sharing.
(XEN) AMD-Vi: IOMMU not found!
(XEN) I/O virtualisation disabled
(XEN) ENABLING IO-APIC IRQs
(XEN)  -> Using new ACK method
(XEN) Platform timer is 14.318MHz HPET
(XEN) Allocated console ring of 64 KiB.
(XEN) HVM: ASIDs enabled.
(XEN) SVM: Supported advanced features:
(XEN)  - Nested Page Tables (NPT)
(XEN)  - Last Branch Record (LBR) Virtualisation
(XEN)  - Next-RIP Saved on #VMEXIT
(XEN)  - Pause-Intercept Filter
(XEN) HVM: SVM enabled
(XEN) HVM: Hardware Assisted Paging (HAP) detected
(XEN) HVM: HAP page sizes: 4kB, 2MB, 1GB
(XEN) Brought up 24 CPUs
(XEN) mtrr: your CPUs had inconsistent variable MTRR settings
(XEN) Xenoprofile: AMD IBS detected (0x1f)
(XEN) *** LOADING DOMAIN 0 ***
(XEN)  Xen  kernel: 64-bit, lsb, compat32
(XEN)  Dom0 kernel: 64-bit, PAE, lsb, paddr 0x1000000 -> 0x1f1a000
(XEN) PHYSICAL MEMORY ARRANGEMENT:
(XEN)  Dom0 alloc.:   0000000214000000->0000000218000000 (2016233 pages to be allocated)
(XEN)  Init. ramdisk: 000000021e787000->000000021ffff4f5
(XEN) VIRTUAL MEMORY ARRANGEMENT:
(XEN)  Loaded kernel: ffffffff81000000->ffffffff81f1a000
(XEN)  Init. ramdisk: ffffffff81f1a000->ffffffff837924f5
(XEN)  Phys-Mach map: ffffffff83793000->ffffffff84721310
(XEN)  Start info:    ffffffff84722000->ffffffff847224b4
(XEN)  Page tables:   ffffffff84723000->ffffffff8474a000
(XEN)  Boot stack:    ffffffff8474a000->ffffffff8474b000
(XEN)  TOTAL:         ffffffff80000000->ffffffff84800000
(XEN)  ENTRY ADDRESS: ffffffff819031f0
(XEN) Dom0 has maximum 24 VCPUs
(XEN) Scrubbing Free RAM: .done.
(XEN) Initial low memory virq threshold set at 0x4000 pages.
(XEN) Std. Loglevel: Errors and warnings
(XEN) Guest Loglevel: Nothing (Rate-limited: Errors and warnings)
(XEN) Xen is relinquishing VGA console.
(XEN) *** Serial input -> DOM0 (type 'CTRL-a' three times to switch input to Xen)
(XEN) Freed 288kB init memory.
(XEN) traps.c:2514:d0 Domain attempted WRMSR 00000000c0010004 from 0x0000000000000000 to 0x000000000000ffff.
(XEN) event_channel.c:271:d0 EVTCHNOP failure: domain 0, error -22
config.xen :
 kernel         = './build/clickos_x86_64'
vcpus          = '1'
vif                 = ['script=vif-openvswitch,mac=00:00:00:00:01:00,bridge=ovs-lan']
name           = 'click3'
on_crash        = "destroy"
on_reboot       = "destroy"
on_poweroff     = "destroy"

it is freezing while i want to create config.xen and when i type xl list it appears in --p state.
when i rebooted it change to --b state and sometime to r-- !!!??
could you please help me, but i try it before in the same machine to many times and it works,
where can i have the basic configuration file to create an image ?
Thank you,
